# Generated by Django 4.0.3 on 2022-12-08 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anwer',
            new_name='Answer',
        ),
    ]
